sync-with-github:
 when: manual
 script:
  - git remote add github $REMOTE_REPOSITORY_URL
  - git fetch github # Fetch all branches from GitHub
  - |
    for branch in $(git ls-remote --heads github | grep -v "HEAD" | awk '{print $2}' | sed 's/refs\/heads\///'); do
      # Checkout the branch
      git checkout $branch
      # Pull latest changes from GitHub
      git pull github $branch
      # Push the branch to GitLab (force push)
      git push -f https://root:$GITLAB_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git $branch
    done
  # Checkout main branch
  - git checkout main
  # Pull latest changes from GitLab
  - git pull origin main
