# Name the node stage "builder"
FROM node:16 AS builder

ARG PORT
# NODE_ENV = dev, prod
ARG NODE_ENV

ARG JUSPAY_SECRET_KEY_PATH
ARG JUSPAY_BASE_URL
ARG JUSPAY_MERCHANT_ID
ARG JUSPAY_API_KEY
ARG RSP_URI
ARG RSP_ID
ARG ESSENTIAL_DASHBOARD_URI
ARG EMAIL_ADDRESS
ARG EMAIL_PASSWORD
ARG CONTACTUS_EMAIL_ADDRESS
ARG SITE_URL
ARG NODE_ENV
ARG LOKI_HOST
ARG JUSPAY_WEBHOOK_USERNAME
ARG JUSPAY_WEBHOOK_PASSWORD
ARG WIL_API_KEY
ARG CLIENT_WEBHOOK_ENDPOINT

ARG FIREBASE_ADMIN_SERVICE_ACCOUNT
ARG REFRESH_TOKEN_URL
ARG GRANT_TYPE

ARG ONDC_BASE_API_URL

ARG DOMAIN
ARG CITY
ARG COUNTRY

ARG BAP_ID
ARG BAP_URL

ARG PROTOCOL_BASE_URL

ARG DB_CONNECTION_STRING

ARG BAP_PRIVATE_KEY
ARG BAP_PUBLIC_KEY
ARG BAP_UNIQUE_KEY_ID
ARG REGISTRY_BASE_URL
ARG ENV_TYPE
ARG BAP_FINDER_FEE_TYPE
ARG BAP_FINDER_FEE_AMOUNT
ARG BAP_GSTNO
ARG SSE_TIMEOUT
ARG MMI_CLIENT_SECRET
ARG MMI_CLIENT_ID
ARG MAP_API_KEY


ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG S3_VERSION
ARG S3_REGION
ARG S3_BUCKET
ARG TWILLIO_ACCOUNT_SID 
ARG TWILLIO_AUTH_TOKEN 
ARG TWILLIO_SENDER_NUMBER
ARG RAZORPAY_KEY_SECRET
ARG RAZORPAY_KEY_ID
ARG RAZORPAY_WEBHOOK_SECRET
ARG BHASHINI_REDIS_PORT
ARG BHASHINI_REDIS_HOST
ARG BHASHINI_USERID
ARG BHASHINI_ULCA_API_KEY
ARG DLT_CUSTOMER_ID
ARG DLT_ENTITY_ID
ARG DLT_USERNAME
ARG DLT_PASSWORD
ARG DLT_SOURCE
ARG DLT_MESSAGE_TYPE
ARG EMAIL_ADDRESS 
ARG EMAIL_PASSWORD
ARG LOKI_HOST

ENV CLIENT_WEBHOOK_ENDPOINT ${CLIENT_WEBHOOK_ENDPOINT}
ENV DLT_CUSTOMER_ID ${DLT_CUSTOMER_ID}
ENV DLT_ENTITY_ID ${DLT_ENTITY_ID}
ENV DLT_USERNAME ${DLT_USERNAME}
ENV DLT_PASSWORD ${DLT_PASSWORD}
ENV DLT_SOURCE ${DLT_SOURCE}
ENV DLT_MESSAGE_TYPE ${DLT_MESSAGE_TYPE}

ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENV S3_VERSION ${S3_VERSION}
ENV S3_REGION ${S3_REGION}
ENV S3_BUCKET ${S3_BUCKET}
ENV TWILLIO_ACCOUNT_SID ${TWILLIO_ACCOUNT_SID}
ENV TWILLIO_AUTH_TOKEN ${TWILLIO_AUTH_TOKEN}
ENV TWILLIO_SENDER_NUMBER ${TWILLIO_SENDER_NUMBER}
ENV EMAIL_ADDRESS ${EMAIL_ADDRESS}
ENV EMAIL_PASSWORD ${EMAIL_PASSWORD}
ENV CONTACTUS_EMAIL_ADDRESS ${CONTACTUS_EMAIL_ADDRESS}
ENV SITE_URL ${SITE_URL}



ENV BHASHINI_REDIS_PORT ${BHASHINI_REDIS_PORT}
ENV BHASHINI_REDIS_HOST ${BHASHINI_REDIS_HOST}
ENV BHASHINI_USERID ${BHASHINI_USERID}
ENV BHASHINI_ULCA_API_KEY ${BHASHINI_ULCA_API_KEY}

ENV PORT ${PORT}
ENV NODE_ENV ${NODE_ENV}

ENV MMI_CLIENT_ID ${MMI_CLIENT_ID}
ENV MMI_CLIENT_SECRET ${MMI_CLIENT_SECRET}
ENV JUSPAY_SECRET_KEY_PATH ${JUSPAY_SECRET_KEY_PATH}
ENV JUSPAY_BASE_URL ${JUSPAY_BASE_URL}
ENV JUSPAY_MERCHANT_ID ${JUSPAY_MERCHANT_ID}
ENV JUSPAY_API_KEY ${JUSPAY_API_KEY}
ENV JUSPAY_WEBHOOK_USERNAME ${JUSPAY_WEBHOOK_USERNAME}
ENV JUSPAY_WEBHOOK_PASSWORD ${JUSPAY_WEBHOOK_PASSWORD}

ENV FIREBASE_ADMIN_SERVICE_ACCOUNT ${FIREBASE_ADMIN_SERVICE_ACCOUNT}
ENV REFRESH_TOKEN_URL ${REFRESH_TOKEN_URL}
ENV GRANT_TYPE ${GRANT_TYPE}

ENV ONDC_BASE_API_URL ${ONDC_BASE_API_URL}

ENV DOMAIN ${DOMAIN}
ENV CITY ${CITY}
ENV COUNTRY ${COUNTRY}
ENV BAP_ID ${BAP_ID}
ENV BAP_URL ${BAP_URL}
ENV PROTOCOL_BASE_URL ${PROTOCOL_BASE_URL}

ENV DB_CONNECTION_STRING ${DB_CONNECTION_STRING}

ENV BAP_PRIVATE_KEY ${BAP_PRIVATE_KEY}
ENV BAP_PUBLIC_KEY ${BAP_PUBLIC_KEY}
ENV BAP_UNIQUE_KEY_ID ${BAP_UNIQUE_KEY_ID}
ENV REGISTRY_BASE_URL ${REGISTRY_BASE_URL}
ENV ENV_TYPE ${ENV_TYPE}
ENV NODE_ENV: ${NODE_ENV}
ENV LOKI_HOST: ${LOKI_HOST}
ENV BAP_FINDER_FEE_TYPE ${BAP_FINDER_FEE_TYPE}
ENV BAP_FINDER_FEE_AMOUNT ${BAP_FINDER_FEE_AMOUNT}
ENV BAP_GSTNO ${BAP_GSTNO}
ENV SSE_TIMEOUT ${SSE_TIMEOUT}
ENV RAZORPAY_KEY_SECRET ${RAZORPAY_KEY_SECRET}
ENV RAZORPAY_KEY_ID ${RAZORPAY_KEY_ID}
ENV MAP_API_KEY ${MAP_API_KEY}
ENV RSP_URI ${RSP_URI}
ENV RSP_ID ${RSP_ID}
ENV ESSENTIAL_DASHBOARD_URI ${ESSENTIAL_DASHBOARD_URI}
ENV EMAIL_ADDRESS ${EMAIL_ADDRESS}
ENV EMAIL_PASSWORD ${EMAIL_PASSWORD}
ENV WIL_API_KEY ${WIL_API_KEY}
ENV TWILLIO_ACCOUNT_SID ${TWILLIO_ACCOUNT_SID}
ENV TWILLIO_AUTH_TOKEN ${TWILLIO_AUTH_TOKEN}
ENV TWILLIO_SENDER_NUMBER ${TWILLIO_SENDER_NUMBER}
ENV RAZORPAY_WEBHOOK_SECRET ${RAZORPAY_WEBHOOK_SECRET}
ENV LOKI_HOST ${LOKI_HOST}

# Set working directory
WORKDIR /build
COPY package*.json yarn.lock ./

# install node modules
RUN rm -f yarn.lock
RUN yarn

# Copy all files from current directory to working dir in image
COPY . .
CMD [ "yarn", "start" ]
